[farcasterd]
bind_port = 7067
bind_ip = "0.0.0.0"

[syncers.testnet]
electrum_server = "ssl://blockstream.info:993"
monero_daemon = "http://stagenet.community.rino.io:38081"
monero_rpc_wallet = "http://walletrpc:38083"
